## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [3]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [4]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [11]:
from sklearn.model_selection import train_test_split
Xtrain_0, Xtest_0, ytrain_0, ytest_0 = train_test_split(X[y==0], y[y==0], test_size=10)
Xtrain_1, Xtest_1, ytrain_1, ytest_1 = train_test_split(X[y==1], y[y==1], test_size=10)

In [16]:
X_test = np.concatenate([Xtest_0, Xtest_1])
y_test = np.concatenate([ytest_0, ytest_1])

In [17]:
X_test

array([[445, 446, 447, 448, 449],
       [815, 816, 817, 818, 819],
       [575, 576, 577, 578, 579],
       [290, 291, 292, 293, 294],
       [420, 421, 422, 423, 424],
       [675, 676, 677, 678, 679],
       [585, 586, 587, 588, 589],
       [960, 961, 962, 963, 964],
       [275, 276, 277, 278, 279],
       [215, 216, 217, 218, 219],
       [ 90,  91,  92,  93,  94],
       [110, 111, 112, 113, 114],
       [130, 131, 132, 133, 134],
       [ 50,  51,  52,  53,  54],
       [195, 196, 197, 198, 199],
       [ 30,  31,  32,  33,  34],
       [125, 126, 127, 128, 129],
       [ 55,  56,  57,  58,  59],
       [175, 176, 177, 178, 179],
       [  0,   1,   2,   3,   4]])

In [18]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])